### ISSUE TITLE
/vendor/autoload.php is missing

### ISSUE THREAD

**Issue by hliljegren** [uoe-dlam/ed-lti-advantage#4]
When trying to activate the plugin I get a fatal error:

Fatal error: require_once(): Failed opening required '/var/www/html/solams/wp-content/plugins/ed-lti-advantage-1.0/classes/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/solams/wp-content/plugins/ed-lti-advantage-1.0/classes/class-ed-lti.php on line 19

And as there are no vendor folder at all I can see why…

Do I need to run any composer command before I can install? Or do you plan to include the "vendor" folder?

**Comment by Sephster** [comment]
Hi @hliljegren - apologies for this. You need to install [Composer](https://getcomposer.org/), the PHP package manager. Once you have this, you can use a command line to navigate to the root of the project and run `composer install`. This will pull down all the supporting packages you need to run the library.

It is common practice in PHP to not bundle dependencies with a library. For us, we wanted to restrict our repository to just our code.

We don't plan on including the vendor directory in the package in future but will leave this ticket open so we can update our installation instructions to include this step. Thank you for highlighting this issue to us

**Comment by hliljegren** [comment]
Thanks! I thought it was so…

**Comment by Sephster** [comment]
This is fixed now in PR #5  - thanks for reporting @hliljegren and fixing @richeduni
